CREATE TABLE IF NOT EXISTS operation_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL COMMENT '操作人 id',
  module VARCHAR(50) NOT NULL COMMENT '模块',
  action VARCHAR(50) NOT NULL COMMENT '动作',
  detail JSON DEFAULT NULL COMMENT '详情 JSON',
  ip VARCHAR(50) DEFAULT NULL COMMENT 'IP 地址',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
