CREATE TABLE IF NOT EXISTS files (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  original_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
  saved_name VARCHAR(255) NOT NULL COMMENT '存储文件名',
  content_type VARCHAR(100) NOT NULL COMMENT '文件类型',
  file_size BIGINT NOT NULL COMMENT '文件大小',
  storage_path VARCHAR(500) NOT NULL COMMENT '存储路径',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
