CREATE TABLE IF NOT EXISTS articles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL COMMENT '文章标题',
  summary VARCHAR(500) DEFAULT NULL COMMENT '文章摘要',
  content MEDIUMTEXT NOT NULL COMMENT '正文',
  author_id BIGINT DEFAULT NULL COMMENT '作者 id',
  status VARCHAR(20) NOT NULL DEFAULT 'draft' COMMENT '文章状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
