-- Day 9: 表设计基础

CREATE DATABASE IF NOT EXISTS ai_admin_demo
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE ai_admin_demo;

DROP TABLE IF EXISTS operation_logs;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE COMMENT '角色名',
  description VARCHAR(255) DEFAULT NULL COMMENT '角色说明',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='角色表';

CREATE TABLE users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '登录用户名',
  password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希',
  nickname VARCHAR(50) NOT NULL COMMENT '昵称',
  email VARCHAR(100) DEFAULT NULL UNIQUE COMMENT '邮箱',
  phone VARCHAR(20) DEFAULT NULL UNIQUE COMMENT '手机号',
  role_id BIGINT NOT NULL COMMENT '角色 id',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1 启用，0 禁用',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  created_by BIGINT DEFAULT NULL COMMENT '创建人 id',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人 id',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_role_id FOREIGN KEY (role_id) REFERENCES roles(id)
) COMMENT='用户表';

CREATE TABLE articles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL COMMENT '文章标题',
  summary VARCHAR(500) DEFAULT NULL COMMENT '文章摘要',
  content MEDIUMTEXT NOT NULL COMMENT '文章正文',
  author_id BIGINT NOT NULL COMMENT '作者 id',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '0 草稿，1 已发布',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  created_by BIGINT DEFAULT NULL COMMENT '创建人 id',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人 id',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_articles_author_id FOREIGN KEY (author_id) REFERENCES users(id)
) COMMENT='文章表';

CREATE TABLE operation_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL COMMENT '操作人 id',
  module VARCHAR(50) NOT NULL COMMENT '模块名',
  action VARCHAR(50) NOT NULL COMMENT '操作动作',
  target_type VARCHAR(50) DEFAULT NULL COMMENT '操作目标类型',
  target_id BIGINT DEFAULT NULL COMMENT '操作目标 id',
  detail JSON DEFAULT NULL COMMENT '操作详情 JSON',
  ip VARCHAR(50) DEFAULT NULL COMMENT 'IP 地址',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_operation_logs_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) COMMENT='操作日志表';
