CREATE TABLE IF NOT EXISTS ai_tasks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_type VARCHAR(50) NOT NULL COMMENT '任务类型',
  status VARCHAR(20) NOT NULL COMMENT '状态',
  input_text MEDIUMTEXT NOT NULL COMMENT '输入内容',
  output_text MEDIUMTEXT DEFAULT NULL COMMENT '输出内容',
  duration_ms INT DEFAULT NULL COMMENT '耗时毫秒数',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME DEFAULT NULL
);
